### ISSUE TITLE
Crash when creating a new node from pin

### ISSUE THREAD

**Issue by MrBrenan** [MothCocoon/FlowGraph#104] opened 2022-05-22 15:24 UTC
Hi Doctor!

It's been some times I was having a crash when dragging from a flow pin, then making a new node from it.
I finally took time to investigate this and found where the error came.

In your AutowireNewNode func (FlowGraphNode.cpp), at some point, the OwningNode of the FromPin gets obliterated.
It happens in the "TryCreateConnection(FromPin, Pin)" of the if statement.

After investigating, it turns out that the TryCreateConnection notifies the graph of a change, without any change having really applied yet.
I haven't looked at who is subscribed to this event, but for some reason, notifying in the middle of the Autowire process breaks a reference.

My fix for the moment was to simply remove the notify.

```
bool UFlowGraphSchema::TryCreateConnection(UEdGraphPin* PinA, UEdGraphPin* PinB) const
{
	const bool bModified = UEdGraphSchema::TryCreateConnection(PinA, PinB);

	if (bModified)
	{
		//PinA->GetOwningNode()->GetGraph()->NotifyGraphChanged();
	}

	return bModified;
}
```

But I guess the right way would be to still notify the graph, but after the autowire process.

I hope this can help!

**Comment by MothDoctor** [comment] 2022-05-23 20:07
@MrBrenan I tried, but cannot reproduce this crash. Is there any specific repro for that?

Theoretically, Owning Node cannot be invalidated why operating on its pin. Yeah, it could cause a lot of crashes. Do you use here your own node spawner class or other editor code?

**Comment by MothDoctor** [comment] 2022-06-13 10:41
Didn't receive a repro in 3 weeks, so closing this ticket.

**Closed by MothDoctor** 2022-06-13 10:41 UTC
Labels: bug fix, editor
