### ISSUE TITLE
Disconnecting a context pin (alt-clicking on it) causes crash

### ISSUE THREAD

**Issue by HomerJohnston** [MothCocoon/FlowGraph#236] opened 2024-10-31 19:23 UTC
This happens from the following call list, starting from top to bottom:
- UFlowGraphSchema::BreakPinLinks(...)
- UFlowGraphNode::NodeConnectionListChanged()
- UFlowGraph::UpdateAsset(...)
- UFlowGraphNode::OnUpdateAsset(...)
- UFlowGraphNode::RebuildRuntimeAddOnsFromEditorSubNodes()
- UFlowGraphNode::RefreshContextPins(...)

... and then it returns to finish off the end of UFlowGraphSchema::BreakPinLinks(...) and actually disconnect the pins. 
I believe that the RefreshContextPins call is destroying pins before the actual disconnection happens. in the end of UFlowGraphSchema::BreakPinLinks(...), it queries the pin for their owning node, which is now null. Editor crashes. 

I don't have a solution for this. My only comment is that it seems odd that a function named "rebuild runtime add-ons" which looks like it is intended to just copy data would need to refresh context pins when done? I may be able to investigate more in the near future.

Repro video:
https://gyazo.com/4b7ba47c29dfb359e904bdd69208a639.mp4

Crash point:
![Crash](https://media.discordapp.net/attachments/818589094392889344/1300148258751905872/image.png?ex=6724662c&is=672314ac&hm=31bc158e2bc445d7d5202deab37aa1f91ab28173965f35bf9de3cf012630f215)

**Comment by MothDoctor** [comment] 2024-12-15 16:55
I cannot reproduce this crash while playing with `UFlowNode_PLayLevelSequence`. It seems that it was fixed by the author of the AddOn feature.

Feel free to open this ticket if you'd encounter a different repo.

**Closed as completed by MothDoctor** 2024-12-15 16:55 UTC
