### ISSUE TITLE
GetContextOutput is modifying assets with no changes

### ISSUE THREAD

**Issue by CBS-pcaporicci** [MothCocoon/FlowGraph#233] opened 2024-10-03 12:33 UTC
Any flow assets that have nodes that are overriding GetContextOutput (eg SubGraph) are coming up modified when I open them, even though nothing has changed. I see they are being marked as modified in UFlowGraphNode::RefreshContextPins.

Reproduction Steps:
1. Create a flow asset (NewFlowAssetSub) and add a custom output (with some text like "test")
2. Create a flow asset (NewFlowAsset) and add a SubGraph node and reference NewFlowAssetSub. Save and close asset.
3. Whenever you reopen NewFlowAsset it will come up modified.

**Comment by MothDoctor** [comment] 2024-12-15 18:37
I cannot reproduce the issue. It seems it was fixed by the author of the AddOn feature.

Feel free to open this ticket if you'd encounter a different repo.

**Closed as completed by MothDoctor** 2024-12-15 18:37 UTC
