### ISSUE TITLE
Copy Pasting comments broken in 5.x

### ISSUE THREAD

**Issue by chriszuko** [MothCocoon/FlowGraph#215] opened 2024-07-15 15:58 UTC
Figured I'd report the issue you can no longer copy paste comment nodes in latest 5.x (using that currently to try out the addon stuffs)
Seems like a simple whoops quickly looking at the code seems to filter purposefully only flow nodes.

**Comment by MothDoctor** [comment] 2024-12-15 17:56
Sorry it took so long, but the issue is now fixed :)

**Closed as completed by MothDoctor** 2024-12-15 17:56 UTC
